{% set name = "Orange3-Network" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dec14f7f14ec16247416c58cc62765081b5410795ebf51d2c83c89c6937f1e66

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy >=1.16.0
  run:
    - python
    - anyqt
    - {{ pin_compatible('numpy') }}
    - gensim
    - orange3 >=3.34
    - orange-widget-base
    - scipy
    - scikit-learn

test:
  imports:
    - orangecontrib.network

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - COPYING

  summary: Networks add-on for Orange 3 data mining software package.
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - astaric
    - kernc
    - primozgodec
    - janezd
