{% set name = "Orange3-Network" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: adeee9d2e0a7545c9bfeb7ddcfed143bdedc731a1b13d59703b541c75a98179e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy >=1.16.0

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gensim
    - orange3 >=3.28

test:
  imports:
    - orangecontrib.network

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - COPYING

  summary: Networks add-on for Orange 3 data mining software package.
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - astaric
    - kernc
    - primozgodec
    - janezd
