{% set name = "Orange3-Network" %}
{% set version = "1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 699c37db7c7e8202c794f0cd5e1952cc3f2ad42354ce527ac806fdaeaa76f1ff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy >=1.16.0
  run:
    - python
    - anyqt
    - {{ pin_compatible('numpy') }}
    - gensim
    - orange3 >=3.35
    - orange-widget-base
    - scipy
    - scikit-learn

test:
  imports:
    - orangecontrib.network

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - COPYING

  summary: Networks add-on for Orange 3 data mining software package.
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - astaric
    - kernc
    - primozgodec
    - janezd
