{% set name = "Orange3-Network" %}
{% set version = "1.4.1" %}
{% set sha256 = "3edd4ae00f443038ad641c7ea7668b7b813294930b87f7c67fd42d984b6ec6b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.*

  run:
    - python
    - numpy >=1.11
    - orange3
    - networkx >=1.10
    - pyqtgraph >=0.9.10

test:
  imports:
    - orangecontrib.network

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0
  summary: 'Networks add-on for Orange 3 data mining software package.'
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - astaric
    - kernc
