{% set name = "Orange3-Network" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e76dc0276b52158dc99abb5674b15da6eb130c6fdcbe1f6c94417dbc51853677

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - numpy
    - numpy >=1.8.0

  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - orange3 >=3.20
    - networkx >=1.10
    - pyqtgraph >=0.9.10

test:
  imports:
    - orangecontrib.network

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0
  license_file:
    - LICENSE
    - COPYING

  summary: Networks add-on for Orange 3 data mining software package.
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - astaric
    - kernc
    - primozgodec
    - janezd
