{% set name = "Orange3-Network" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 02710f651bcd6793e81f7e50add15058216c396953068ff88da55500c4758652

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py>=313]  # gensim currently not available

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - trubar >=0.3.3
  run:
    - python
    - anyqt
    - numpy
    - gensim
    - orange3 >=3.38.1
    - orange-widget-base
    - pyqtgraph
    - scipy
    - scikit-learn

test:
  imports:
    - orangecontrib.network

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - COPYING

  summary: Networks add-on for Orange 3 data mining software package.
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - markotoplak
    - astaric
    - kernc
    - primozgodec
    - janezd
