{% set name = "Orange3-Network" %}
{% set version = "1.3.0" %}
{% set sha256 = "2879b5cf8e31ef2f7f7f9c00d8fc99ae2c3df92909ce27098527edd6d7fcac79" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - orange3
    - networkx >=1.10
    - pyqtgraph >=0.9.10

test:
  imports:
    - orangecontrib.network
    - orangecontrib.network._fr_layout

about:
  home: https://github.com/biolab/orange3-network
  license: GPL-3.0
  summary: 'Networks add-on for Orange 3 data mining software package.'
  license_family: GPL
  doc_url: http://orange3-network.rtfd.io/
  dev_url: https://github.com/biolab/orange3-network

extra:
  recipe-maintainers:
    - astaric
    - kernc
