appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ggBZuf3AJNH7W5P73o3PBpaBON4Oq+ccrGjRoOL/zl9ZtK3LHth3d/V2IRI1dEF69eqobf+1j7MxT6LyWhbiGW3QzVGO94qCsUXxWsx7r0Wjip7BNPvov9OMA+9dmUZWL3ALJSqWeGQ6POkbo/MrLP0wWHjc6m9fDYH/Lr2QgKEG2HaGV0yimx3qt7yQ3hA7/NpVQQjwJl/GnYaoF4vMxG0HwfuG/Pa05euJIpA3vaqTxDyZ32tGEs5v875aEuMM/EhbgbmWE1acy20zoRXR7GYbXrRIAoF1ZGMqtjuZXMuG2Boc0R5i7ivJDcGxN/s+m4bPI8TkNWuxMb8G4gCWl+0KghrXXXIrL15XhSqkCMg16+gFozVxFQg2D3LazerROAfBFqEIP96QJ4XYwD7naSBer6nbf2Zi8/nlJZy75fbQzeEZtf0eqAOg/Z7LbOIK3LBTYi/NaZHbSFHlpUicVvfYbFZ/rzTpZ7VkyPqf4vmSohVEBzlPtPKzn8wEb6x58GrUQ7EBJGui/GNzMtFq3FXWL0zU4N4trqrjVURKjfUUPKObhjlxSeI4vYzYzmLJ+OGk9sfNftMbCp07JLga6G3dgB+EZvniflZ4O91oTPY0Tevy6MH4kigoSB9ygvDRvx8Apgp8aYpc+jDGv84VE2fZ4xe8vSBBpcfa54VXdgs=}
